#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [[ -z "$SKIP_PUSH" || $(($SKIP_PUSH % 2)) -eq 0 ]]; then
  export SKIP_PUSH=$((SKIP_PUSH + 1))
  npm run push2
else
  export SKIP_PUSH=$((SKIP_PUSH + 1))
fi
